#!/usr/bin/env bash
set -euo pipefail

# Get the location of the script so we know where to set things up from
SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"
CLI_DIR="${SCRIPT_DIR}/cli"

# Files for the venv hashing
REQUIREMENTS_FILE="${CLI_DIR}/requirements.txt"
VENV_DIR="${CLI_DIR}/venv"
HASH_FILE="${VENV_DIR}/requirements_hash"

# Install nix if necessary
NIX_BIN="$HOME/.nix-profile/bin"
if [[ ! -d "$HOME/.nix-profile" ]]; then
    curl -L https://nixos.org/nix/install | sh

    # Install Python with nix (we should probably check the Python version here)
    $NIX_BIN/nix-channel --update
    $NIX_BIN/nix-env -iA pkgs.python310
fi

. $HOME/.nix-profile/etc/profile.d/nix.sh

# Check if we need to setup the virtual environment
CURRENT_REQUIREMENTS_HASH=$(sha1sum $REQUIREMENTS_FILE | awk '{print $1}')

if [[ ! -d $VENV_DIR ]]; then
    SETUP_REQUIRED=true
elif [[ ! -f $HASH_FILE ]]; then
    SETUP_REQUIRED=true
elif [[ $(cat $HASH_FILE) != $CURRENT_REQUIREMENTS_HASH ]]; then
    SETUP_REQUIRED=true
else
    SETUP_REQUIRED=false
fi

# Install the dependencies for the CLI
if [[ $SETUP_REQUIRED == "true" ]]; then
    echo "Updating virtual environment..."
    $NIX_BIN/python -m venv $VENV_DIR
    $VENV_DIR/bin/pip install --quiet -r $REQUIREMENTS_FILE

    echo $CURRENT_REQUIREMENTS_HASH > $HASH_FILE
fi

# Run the CLI
$VENV_DIR/bin/python $CLI_DIR/cli.py $@
