#!/bin/bash

# Set the location of the repository on github
repository_location="gizmo385/dotfiles"
repository_branch="master"

# In the repository, this is the folder that contains the dotfiles to copy
dotfiles_folder="dotfiles"

# Check that git is installed
command -v git > /dev/null 2>&1
if (( $? != 0 )) ; then
    echo Git is required to update dotfiles 1>&2
    exit 1
fi

# Clone dotfiles if they aren't present
if [ ! -d "$HOME/.dotfiles" ]; then
    # Clone the dotfiles
    echo Cloning remote dotfiles...
    git clone --recursive https://github.com/${repository_location} -b ${repository_branch} ${HOME}/.dotfiles
    git_exit_status=$?
fi

# Pull the most updated copy
cd $HOME/.dotfiles && git pull
git_exit_status=$?

# If the clone/pull operation failed, exit with the exit status provided by git
if (( $git_exit_status != 0 )) ; then
    echo There was an error while attempting to clone/pull dotfiles! 1>&2
    exit $git_exit_status
fi

# Symlink all the files
echo Symlinking dotfiles into ${HOME}
ln -sf $HOME/.dotfiles/dotfiles/.[!.]* $HOME

if [ ! -d "$HOME/.vim/bundle/vundle" ]; then
    echo "Installing Vundle (plugin manager)"
    git clone https://github.com/gmarik/Vundle.vim $HOME/.vim/bundle/vundle > /dev/null 2>&1
fi

# Symlink nixpkgs file
ln -s dotfiles/.nixpkgs/darwin-configuration.nix $HOME/.nixpkgs/darwin-configuration.nix

echo Run :BundleInstall upon starting vim if plugins aren\'t installed.

echo Finished installing dotfiles. Please source the relevant files for your shell.
