# Setting up oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="crcandy"
plugins=()
source $ZSH/oh-my-zsh.sh

# Forming the path
export PATH=$PATH:"/bin"
export PATH=$PATH:"/opt/local/bin"
export PATH=$PATH:"/sbin"
export PATH=$PATH:"/usr/bin"
export PATH=$PATH:"/usr/games"
export PATH=$PATH:"/usr/local/bin"
export PATH=$PATH:"/usr/local/sbin"
export PATH=$PATH:"/usr/sbin"
export PATH=$PATH:"/nix/var/nix/profiles/default/bin/"
export PATH=$PATH:"$HOME/.local/bin"
export PATH=$PATH:"$HOME/scripts"

# Shhh don't let anyone know where I keep my monorepo clone :P
export PATH=$PATH:"$HOME/workspace/discord/.local/bin"

# Backgrounding and foregrounding with ctrl-z
fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

# Setting ctrl-f for the fzf file-finder
bindkey '^F' fzf-file-widget

# Disable retrieving git status in prompt
git config --global --replace-all oh-my-zsh.hide-status 1
git config --global --replace-all oh-my-zsh.hide-dirty 1

# Use the zsh iterm integration, if present
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Setting up normal nix
if [ -e ${HOME}/.nix-profile/etc/profile.d/nix.sh ]; then . ${HOME}/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

# Ensure that our keybindings are being properly installed
fpath=($fpath "${HOME}/.zfunctions")
if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
fi

# Setup home-manager
source /etc/profiles/per-user/$USER/etc/profile.d/hm-session-vars.sh

# Add our aliases
source $HOME/shell_aliases

# Neovim is better than normal vim
if command -v nvim > /dev/null 2>&1; then
    export VISUAL=nvim
    alias vim=nvim
else
    export VISUAL=vim
fi
export EDITOR="$VISUAL"

# We want to prefer bat as a cat alternative, if it is installed
if command -v bat > /dev/null 2>&1; then
    alias cat=bat
fi
